/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) example_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[8] = {5, 1, 0, 4, 1, 2, 3, 4};

/* example_model_expl_vde_adj:(i0[4],i1[4],i2,i3[0])->(o0[5x1,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 4, w00);
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  w01 = w00[0];
  w02 = w00[1];
  w03 = w00[2];
  w04 = w00[3];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: @1 = 137.3 */
  w01 = 1.3730000000000001e+02;
  /* #4: @1 = (@1*@4) */
  w01 *= w04;
  /* #5: @5 = (-@1) */
  w05 = (- w01 );
  /* #6: @6 = 0.0012 */
  w06 = 1.1999999999999999e-03;
  /* #7: @7 = input[0][3] */
  w07 = arg[0] ? arg[0][3] : 0;
  /* #8: @7 = (@7*@4) */
  w07 *= w04;
  /* #9: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #10: @5 = (@5-@7) */
  w05 -= w07;
  /* #11: @7 = input[0][2] */
  w07 = arg[0] ? arg[0][2] : 0;
  /* #12: @8 = (2.*@7) */
  w08 = (2.* w07 );
  /* #13: @9 = 8.79e-07 */
  w09 = 8.7899999999999997e-07;
  /* #14: @10 = 0.333333 */
  w10 = 3.3333333333333331e-01;
  /* #15: @10 = (@10*@2) */
  w10 *= w02;
  /* #16: @9 = (@9*@10) */
  w09 *= w10;
  /* #17: @8 = (@8*@9) */
  w08 *= w09;
  /* #18: @5 = (@5+@8) */
  w05 += w08;
  /* #19: output[0][1] = @5 */
  if (res[0]) res[0][1] = w05;
  /* #20: @5 = 12.17 */
  w05 = 1.2170000000000000e+01;
  /* #21: @6 = (@6*@7) */
  w06 *= w07;
  /* #22: @5 = (@5+@6) */
  w05 += w06;
  /* #23: @5 = (@5*@4) */
  w05 *= w04;
  /* #24: @3 = (@3-@5) */
  w03 -= w05;
  /* #25: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #26: output[0][3] = @1 */
  if (res[0]) res[0][3] = w01;
  return 0;
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int example_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int example_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real example_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* example_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* example_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* example_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* example_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 14;
  return 0;
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 14*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
