/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) example_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {4, 4, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

static const casadi_real casadi_zeros[16] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* example_model_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[0])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, *w11=w+32, *w12=w+36, w13;
  casadi_real w14;
  const casadi_real *cs, *wr08, *wr09, *wr10, *wr11, *wr12;
  /* #0: @0 = input[0][1] */
  w00 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = -9.81 */
  w00 = -9.8100000000000005e+00;
  /* #3: @1 = 8.79e-07 */
  w01 = 8.7899999999999997e-07;
  /* #4: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #5: @3 = sq(@2) */
  w03 = casadi_sq( w02 );
  /* #6: @3 = (@1*@3) */
  w03  = (w01*w03);
  /* #7: @4 = 3 */
  w04 = 3.;
  /* #8: @3 = (@3/@4) */
  w03 /= w04;
  /* #9: @0 = (@0+@3) */
  w00 += w03;
  /* #10: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #11: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #12: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #13: @3 = 137.3 */
  w03 = 1.3730000000000001e+02;
  /* #14: @4 = input[3][0] */
  w04 = arg[3] ? arg[3][0] : 0;
  /* #15: @4 = (@4-@2) */
  w04 -= w02;
  /* #16: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #17: @5 = 12.17 */
  w05 = 1.2170000000000000e+01;
  /* #18: @6 = 0.0012 */
  w06 = 1.1999999999999999e-03;
  /* #19: @7 = (@6*@2) */
  w07  = (w06*w02);
  /* #20: @5 = (@5+@7) */
  w05 += w07;
  /* #21: @7 = (@5*@0) */
  w07  = (w05*w00);
  /* #22: @4 = (@4-@7) */
  w04 -= w07;
  /* #23: output[0][3] = @4 */
  if (res[0]) res[0][3] = w04;
  /* #24: @8 = input[1][0] */
  wr08 = arg[1] ? arg[1] : casadi_zeros;
  /* #25: {@9, @10, @11, @12} = horzsplit(@8) */
  wr09 = wr08;
  wr10 = wr08+4;
  wr11 = wr08+8;
  wr12 = wr08+12;
  /* #26: {NULL, @4, @7, @13} = vertsplit(@9) */
  w04 = wr09[1];
  w07 = wr09[2];
  w13 = wr09[3];
  /* #27: output[1][0] = @4 */
  if (res[1]) res[1][0] = w04;
  /* #28: @4 = 0.333333 */
  w04 = 3.3333333333333331e-01;
  /* #29: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #30: @14 = (@2*@7) */
  w14  = (w02*w07);
  /* #31: @14 = (@1*@14) */
  w14  = (w01*w14);
  /* #32: @14 = (@4*@14) */
  w14  = (w04*w14);
  /* #33: output[1][1] = @14 */
  if (res[1]) res[1][1] = w14;
  /* #34: output[1][2] = @13 */
  if (res[1]) res[1][2] = w13;
  /* #35: @14 = (@6*@7) */
  w14  = (w06*w07);
  /* #36: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #37: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #38: @14 = (@14+@13) */
  w14 += w13;
  /* #39: @14 = (-@14) */
  w14 = (- w14 );
  /* #40: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #41: @14 = (@14-@7) */
  w14 -= w07;
  /* #42: output[1][3] = @14 */
  if (res[1]) res[1][3] = w14;
  /* #43: {NULL, @14, @7, @13} = vertsplit(@10) */
  w14 = wr10[1];
  w07 = wr10[2];
  w13 = wr10[3];
  /* #44: output[1][4] = @14 */
  if (res[1]) res[1][4] = w14;
  /* #45: @14 = (@2*@7) */
  w14  = (w02*w07);
  /* #46: @14 = (@1*@14) */
  w14  = (w01*w14);
  /* #47: @14 = (@4*@14) */
  w14  = (w04*w14);
  /* #48: output[1][5] = @14 */
  if (res[1]) res[1][5] = w14;
  /* #49: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #50: @14 = (@6*@7) */
  w14  = (w06*w07);
  /* #51: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #52: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #53: @14 = (@14+@13) */
  w14 += w13;
  /* #54: @14 = (-@14) */
  w14 = (- w14 );
  /* #55: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #56: @14 = (@14-@7) */
  w14 -= w07;
  /* #57: output[1][7] = @14 */
  if (res[1]) res[1][7] = w14;
  /* #58: {NULL, @14, @7, @13} = vertsplit(@11) */
  w14 = wr11[1];
  w07 = wr11[2];
  w13 = wr11[3];
  /* #59: output[1][8] = @14 */
  if (res[1]) res[1][8] = w14;
  /* #60: @14 = (@2*@7) */
  w14  = (w02*w07);
  /* #61: @14 = (@1*@14) */
  w14  = (w01*w14);
  /* #62: @14 = (@4*@14) */
  w14  = (w04*w14);
  /* #63: output[1][9] = @14 */
  if (res[1]) res[1][9] = w14;
  /* #64: output[1][10] = @13 */
  if (res[1]) res[1][10] = w13;
  /* #65: @14 = (@6*@7) */
  w14  = (w06*w07);
  /* #66: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #67: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #68: @14 = (@14+@13) */
  w14 += w13;
  /* #69: @14 = (-@14) */
  w14 = (- w14 );
  /* #70: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #71: @14 = (@14-@7) */
  w14 -= w07;
  /* #72: output[1][11] = @14 */
  if (res[1]) res[1][11] = w14;
  /* #73: {NULL, @14, @7, @13} = vertsplit(@12) */
  w14 = wr12[1];
  w07 = wr12[2];
  w13 = wr12[3];
  /* #74: output[1][12] = @14 */
  if (res[1]) res[1][12] = w14;
  /* #75: @14 = (@2*@7) */
  w14  = (w02*w07);
  /* #76: @14 = (@1*@14) */
  w14  = (w01*w14);
  /* #77: @14 = (@4*@14) */
  w14  = (w04*w14);
  /* #78: output[1][13] = @14 */
  if (res[1]) res[1][13] = w14;
  /* #79: output[1][14] = @13 */
  if (res[1]) res[1][14] = w13;
  /* #80: @14 = (@6*@7) */
  w14  = (w06*w07);
  /* #81: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #82: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #83: @14 = (@14+@13) */
  w14 += w13;
  /* #84: @14 = (-@14) */
  w14 = (- w14 );
  /* #85: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #86: @14 = (@14-@7) */
  w14 -= w07;
  /* #87: output[1][15] = @14 */
  if (res[1]) res[1][15] = w14;
  /* #88: @14 = zeros(1x4,1nz) */
  w14 = 0.;
  /* #89: (@14[0] = @3) */
  for (rr=(&w14)+0, cs=(&w03); rr!=(&w14)+1; rr+=1) *rr = *cs++;
  /* #90: @14 = @14' */
  /* #91: @12 = dense(@14) */
  casadi_densify((&w14), casadi_s0, w12, 0);
  /* #92: @11 = input[2][0] */
  casadi_copy(arg[2], 4, w11);
  /* #93: {NULL, @14, @7, @13} = vertsplit(@11) */
  w14 = w11[1];
  w07 = w11[2];
  w13 = w11[3];
  /* #94: @2 = (@2*@7) */
  w02 *= w07;
  /* #95: @1 = (@1*@2) */
  w01 *= w02;
  /* #96: @4 = (@4*@1) */
  w04 *= w01;
  /* #97: @6 = (@6*@7) */
  w06 *= w07;
  /* #98: @0 = (@0*@6) */
  w00 *= w06;
  /* #99: @5 = (@5*@13) */
  w05 *= w13;
  /* #100: @0 = (@0+@5) */
  w00 += w05;
  /* #101: @0 = (-@0) */
  w00 = (- w00 );
  /* #102: @3 = (@3*@7) */
  w03 *= w07;
  /* #103: @0 = (@0-@3) */
  w00 -= w03;
  /* #104: @11 = vertcat(@14, @4, @13, @0) */
  rr=w11;
  *rr++ = w14;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w00;
  /* #105: @12 = (@12+@11) */
  for (i=0, rr=w12, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #106: output[2][0] = @12 */
  casadi_copy(w12, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void example_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int example_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int example_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real example_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* example_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* example_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* example_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* example_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 42;
  return 0;
}

CASADI_SYMBOL_EXPORT int example_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 42*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
